-- =============================================
-- Clublabs Intelligence - 19-Step ERS Funnel
-- Detailed chatbot flow tracking
-- =============================================

USE ROLE ACCOUNTADMIN;
USE DATABASE CLUBLABS_INTELLIGENCE;
USE WAREHOUSE CLUBLABS_WH;

-- =============================================
-- DIMENSION: Funnel Steps (19 Steps)
-- =============================================

CREATE OR REPLACE TABLE ANALYTICS.DIM_FUNNEL_STEP (
    STEP_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    STEP_NUMBER NUMBER NOT NULL UNIQUE,
    STEP_CODE VARCHAR(50) NOT NULL UNIQUE,
    STEP_NAME VARCHAR(100) NOT NULL,
    STEP_CATEGORY VARCHAR(50),
    IS_CRITICAL BOOLEAN DEFAULT FALSE,
    EXPECTED_COMPLETION_SECONDS NUMBER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Insert the 19-step ERS chatbot flow
INSERT INTO ANALYTICS.DIM_FUNNEL_STEP (STEP_NUMBER, STEP_CODE, STEP_NAME, STEP_CATEGORY, IS_CRITICAL, EXPECTED_COMPLETION_SECONDS)
VALUES 
    (1, 'LANDING', 'Landing Page Arrival', 'Entry', TRUE, 5),
    (2, 'CHAT_INIT', 'Chat Widget Opened', 'Entry', TRUE, 10),
    (3, 'WELCOME_MSG', 'Welcome Message Displayed', 'Greeting', FALSE, 3),
    (4, 'MEMBER_AUTH', 'Member Authentication', 'Authentication', TRUE, 30),
    (5, 'MEMBER_VERIFIED', 'Member Verified', 'Authentication', TRUE, 5),
    (6, 'INTENT_PROMPT', 'Intent Selection Prompt', 'Intent', FALSE, 5),
    (7, 'INTENT_SELECTED', 'Intent Selected by User', 'Intent', TRUE, 15),
    (8, 'INTENT_CONFIRMED', 'Intent Confirmed by Bot', 'Intent', FALSE, 3),
    (9, 'LOCATION_PROMPT', 'Location Request', 'Data Collection', FALSE, 5),
    (10, 'LOCATION_PROVIDED', 'Location Provided', 'Data Collection', TRUE, 45),
    (11, 'LOCATION_VERIFIED', 'Location Verified', 'Data Collection', FALSE, 10),
    (12, 'VEHICLE_PROMPT', 'Vehicle Info Request', 'Data Collection', FALSE, 5),
    (13, 'VEHICLE_PROVIDED', 'Vehicle Info Provided', 'Data Collection', TRUE, 30),
    (14, 'SERVICE_DETAILS', 'Service Details Shown', 'Service', FALSE, 5),
    (15, 'SERVICE_CONFIRMED', 'Service Confirmed', 'Service', TRUE, 20),
    (16, 'DISPATCH_INITIATED', 'Dispatch Initiated', 'Dispatch', TRUE, 10),
    (17, 'ETA_PROVIDED', 'ETA Provided to Member', 'Dispatch', FALSE, 5),
    (18, 'CONFIRMATION_SENT', 'Confirmation Sent', 'Completion', FALSE, 3),
    (19, 'SESSION_COMPLETE', 'Session Completed Successfully', 'Completion', TRUE, 5);

-- =============================================
-- FACT: Detailed Funnel Events
-- =============================================

CREATE OR REPLACE TABLE ANALYTICS.FACT_FUNNEL_EVENT (
    EVENT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    SESSION_ID VARCHAR(50) NOT NULL,
    CONVERSATION_KEY NUMBER REFERENCES ANALYTICS.FACT_CONVERSATION(CONVERSATION_KEY),
    MEMBER_KEY NUMBER REFERENCES ANALYTICS.DIM_MEMBER(MEMBER_KEY),
    STEP_KEY NUMBER REFERENCES ANALYTICS.DIM_FUNNEL_STEP(STEP_KEY),
    DATE_KEY NUMBER(8) REFERENCES ANALYTICS.DIM_DATE(DATE_KEY),
    CHANNEL_KEY NUMBER REFERENCES ANALYTICS.DIM_CHANNEL(CHANNEL_KEY),
    
    EVENT_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    STEP_DURATION_SECONDS NUMBER,
    CUMULATIVE_DURATION_SECONDS NUMBER,
    
    WAS_SUCCESSFUL BOOLEAN DEFAULT TRUE,
    ERROR_CODE VARCHAR(50),
    ERROR_MESSAGE VARCHAR(500),
    
    USER_INPUT TEXT,
    BOT_RESPONSE TEXT,
    CONFIDENCE_SCORE FLOAT,
    
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================
-- FACT: Session-Level Funnel Summary
-- =============================================

CREATE OR REPLACE TABLE ANALYTICS.FACT_FUNNEL_SESSION (
    SESSION_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    SESSION_ID VARCHAR(50) NOT NULL UNIQUE,
    CONVERSATION_KEY NUMBER REFERENCES ANALYTICS.FACT_CONVERSATION(CONVERSATION_KEY),
    MEMBER_KEY NUMBER REFERENCES ANALYTICS.DIM_MEMBER(MEMBER_KEY),
    DATE_KEY NUMBER(8) REFERENCES ANALYTICS.DIM_DATE(DATE_KEY),
    CHANNEL_KEY NUMBER REFERENCES ANALYTICS.DIM_CHANNEL(CHANNEL_KEY),
    
    SESSION_START TIMESTAMP_NTZ,
    SESSION_END TIMESTAMP_NTZ,
    TOTAL_DURATION_SECONDS NUMBER,
    
    STEPS_COMPLETED NUMBER,
    MAX_STEP_REACHED NUMBER,
    DROP_OFF_STEP NUMBER,
    DROP_OFF_REASON VARCHAR(200),
    
    STEP_1_LANDING BOOLEAN DEFAULT FALSE,
    STEP_2_CHAT_INIT BOOLEAN DEFAULT FALSE,
    STEP_3_WELCOME_MSG BOOLEAN DEFAULT FALSE,
    STEP_4_MEMBER_AUTH BOOLEAN DEFAULT FALSE,
    STEP_5_MEMBER_VERIFIED BOOLEAN DEFAULT FALSE,
    STEP_6_INTENT_PROMPT BOOLEAN DEFAULT FALSE,
    STEP_7_INTENT_SELECTED BOOLEAN DEFAULT FALSE,
    STEP_8_INTENT_CONFIRMED BOOLEAN DEFAULT FALSE,
    STEP_9_LOCATION_PROMPT BOOLEAN DEFAULT FALSE,
    STEP_10_LOCATION_PROVIDED BOOLEAN DEFAULT FALSE,
    STEP_11_LOCATION_VERIFIED BOOLEAN DEFAULT FALSE,
    STEP_12_VEHICLE_PROMPT BOOLEAN DEFAULT FALSE,
    STEP_13_VEHICLE_PROVIDED BOOLEAN DEFAULT FALSE,
    STEP_14_SERVICE_DETAILS BOOLEAN DEFAULT FALSE,
    STEP_15_SERVICE_CONFIRMED BOOLEAN DEFAULT FALSE,
    STEP_16_DISPATCH_INITIATED BOOLEAN DEFAULT FALSE,
    STEP_17_ETA_PROVIDED BOOLEAN DEFAULT FALSE,
    STEP_18_CONFIRMATION_SENT BOOLEAN DEFAULT FALSE,
    STEP_19_SESSION_COMPLETE BOOLEAN DEFAULT FALSE,
    
    IS_COMPLETE BOOLEAN DEFAULT FALSE,
    WAS_ESCALATED BOOLEAN DEFAULT FALSE,
    
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================
-- VIEW: 19-Step Funnel Analysis
-- =============================================

CREATE OR REPLACE VIEW ANALYTICS.V_19_STEP_FUNNEL AS
SELECT 
    dd.FULL_DATE AS DATE,
    dd.MONTH_NAME,
    dd.YEAR,
    dc.CHANNEL_NAME,
    
    COUNT(DISTINCT ffs.SESSION_ID) AS TOTAL_SESSIONS,
    
    SUM(CASE WHEN ffs.STEP_1_LANDING THEN 1 ELSE 0 END) AS STEP_01_LANDING,
    SUM(CASE WHEN ffs.STEP_2_CHAT_INIT THEN 1 ELSE 0 END) AS STEP_02_CHAT_INIT,
    SUM(CASE WHEN ffs.STEP_3_WELCOME_MSG THEN 1 ELSE 0 END) AS STEP_03_WELCOME_MSG,
    SUM(CASE WHEN ffs.STEP_4_MEMBER_AUTH THEN 1 ELSE 0 END) AS STEP_04_MEMBER_AUTH,
    SUM(CASE WHEN ffs.STEP_5_MEMBER_VERIFIED THEN 1 ELSE 0 END) AS STEP_05_MEMBER_VERIFIED,
    SUM(CASE WHEN ffs.STEP_6_INTENT_PROMPT THEN 1 ELSE 0 END) AS STEP_06_INTENT_PROMPT,
    SUM(CASE WHEN ffs.STEP_7_INTENT_SELECTED THEN 1 ELSE 0 END) AS STEP_07_INTENT_SELECTED,
    SUM(CASE WHEN ffs.STEP_8_INTENT_CONFIRMED THEN 1 ELSE 0 END) AS STEP_08_INTENT_CONFIRMED,
    SUM(CASE WHEN ffs.STEP_9_LOCATION_PROMPT THEN 1 ELSE 0 END) AS STEP_09_LOCATION_PROMPT,
    SUM(CASE WHEN ffs.STEP_10_LOCATION_PROVIDED THEN 1 ELSE 0 END) AS STEP_10_LOCATION_PROVIDED,
    SUM(CASE WHEN ffs.STEP_11_LOCATION_VERIFIED THEN 1 ELSE 0 END) AS STEP_11_LOCATION_VERIFIED,
    SUM(CASE WHEN ffs.STEP_12_VEHICLE_PROMPT THEN 1 ELSE 0 END) AS STEP_12_VEHICLE_PROMPT,
    SUM(CASE WHEN ffs.STEP_13_VEHICLE_PROVIDED THEN 1 ELSE 0 END) AS STEP_13_VEHICLE_PROVIDED,
    SUM(CASE WHEN ffs.STEP_14_SERVICE_DETAILS THEN 1 ELSE 0 END) AS STEP_14_SERVICE_DETAILS,
    SUM(CASE WHEN ffs.STEP_15_SERVICE_CONFIRMED THEN 1 ELSE 0 END) AS STEP_15_SERVICE_CONFIRMED,
    SUM(CASE WHEN ffs.STEP_16_DISPATCH_INITIATED THEN 1 ELSE 0 END) AS STEP_16_DISPATCH_INITIATED,
    SUM(CASE WHEN ffs.STEP_17_ETA_PROVIDED THEN 1 ELSE 0 END) AS STEP_17_ETA_PROVIDED,
    SUM(CASE WHEN ffs.STEP_18_CONFIRMATION_SENT THEN 1 ELSE 0 END) AS STEP_18_CONFIRMATION_SENT,
    SUM(CASE WHEN ffs.STEP_19_SESSION_COMPLETE THEN 1 ELSE 0 END) AS STEP_19_SESSION_COMPLETE,
    
    ROUND(SUM(CASE WHEN ffs.STEP_19_SESSION_COMPLETE THEN 1 ELSE 0 END)::FLOAT / 
          NULLIF(SUM(CASE WHEN ffs.STEP_1_LANDING THEN 1 ELSE 0 END), 0) * 100, 2) AS COMPLETION_RATE_PCT,
    
    AVG(ffs.TOTAL_DURATION_SECONDS) AS AVG_SESSION_DURATION_SECONDS,
    AVG(ffs.STEPS_COMPLETED) AS AVG_STEPS_COMPLETED
FROM ANALYTICS.FACT_FUNNEL_SESSION ffs
JOIN ANALYTICS.DIM_DATE dd ON ffs.DATE_KEY = dd.DATE_KEY
JOIN ANALYTICS.DIM_CHANNEL dc ON ffs.CHANNEL_KEY = dc.CHANNEL_KEY
GROUP BY dd.FULL_DATE, dd.MONTH_NAME, dd.YEAR, dc.CHANNEL_NAME;

-- =============================================
-- VIEW: Step-by-Step Conversion Rates
-- =============================================

CREATE OR REPLACE VIEW ANALYTICS.V_FUNNEL_CONVERSION_RATES AS
WITH step_counts AS (
    SELECT 
        dd.FULL_DATE,
        dc.CHANNEL_NAME,
        SUM(CASE WHEN ffs.STEP_1_LANDING THEN 1 ELSE 0 END) AS S1,
        SUM(CASE WHEN ffs.STEP_2_CHAT_INIT THEN 1 ELSE 0 END) AS S2,
        SUM(CASE WHEN ffs.STEP_3_WELCOME_MSG THEN 1 ELSE 0 END) AS S3,
        SUM(CASE WHEN ffs.STEP_4_MEMBER_AUTH THEN 1 ELSE 0 END) AS S4,
        SUM(CASE WHEN ffs.STEP_5_MEMBER_VERIFIED THEN 1 ELSE 0 END) AS S5,
        SUM(CASE WHEN ffs.STEP_6_INTENT_PROMPT THEN 1 ELSE 0 END) AS S6,
        SUM(CASE WHEN ffs.STEP_7_INTENT_SELECTED THEN 1 ELSE 0 END) AS S7,
        SUM(CASE WHEN ffs.STEP_8_INTENT_CONFIRMED THEN 1 ELSE 0 END) AS S8,
        SUM(CASE WHEN ffs.STEP_9_LOCATION_PROMPT THEN 1 ELSE 0 END) AS S9,
        SUM(CASE WHEN ffs.STEP_10_LOCATION_PROVIDED THEN 1 ELSE 0 END) AS S10,
        SUM(CASE WHEN ffs.STEP_11_LOCATION_VERIFIED THEN 1 ELSE 0 END) AS S11,
        SUM(CASE WHEN ffs.STEP_12_VEHICLE_PROMPT THEN 1 ELSE 0 END) AS S12,
        SUM(CASE WHEN ffs.STEP_13_VEHICLE_PROVIDED THEN 1 ELSE 0 END) AS S13,
        SUM(CASE WHEN ffs.STEP_14_SERVICE_DETAILS THEN 1 ELSE 0 END) AS S14,
        SUM(CASE WHEN ffs.STEP_15_SERVICE_CONFIRMED THEN 1 ELSE 0 END) AS S15,
        SUM(CASE WHEN ffs.STEP_16_DISPATCH_INITIATED THEN 1 ELSE 0 END) AS S16,
        SUM(CASE WHEN ffs.STEP_17_ETA_PROVIDED THEN 1 ELSE 0 END) AS S17,
        SUM(CASE WHEN ffs.STEP_18_CONFIRMATION_SENT THEN 1 ELSE 0 END) AS S18,
        SUM(CASE WHEN ffs.STEP_19_SESSION_COMPLETE THEN 1 ELSE 0 END) AS S19
    FROM ANALYTICS.FACT_FUNNEL_SESSION ffs
    JOIN ANALYTICS.DIM_DATE dd ON ffs.DATE_KEY = dd.DATE_KEY
    JOIN ANALYTICS.DIM_CHANNEL dc ON ffs.CHANNEL_KEY = dc.CHANNEL_KEY
    GROUP BY dd.FULL_DATE, dc.CHANNEL_NAME
)
SELECT 
    FULL_DATE,
    CHANNEL_NAME,
    S1 AS STEP_01_COUNT,
    ROUND(S2::FLOAT / NULLIF(S1, 0) * 100, 2) AS STEP_01_TO_02_RATE,
    ROUND(S3::FLOAT / NULLIF(S2, 0) * 100, 2) AS STEP_02_TO_03_RATE,
    ROUND(S4::FLOAT / NULLIF(S3, 0) * 100, 2) AS STEP_03_TO_04_RATE,
    ROUND(S5::FLOAT / NULLIF(S4, 0) * 100, 2) AS STEP_04_TO_05_RATE,
    ROUND(S6::FLOAT / NULLIF(S5, 0) * 100, 2) AS STEP_05_TO_06_RATE,
    ROUND(S7::FLOAT / NULLIF(S6, 0) * 100, 2) AS STEP_06_TO_07_RATE,
    ROUND(S8::FLOAT / NULLIF(S7, 0) * 100, 2) AS STEP_07_TO_08_RATE,
    ROUND(S9::FLOAT / NULLIF(S8, 0) * 100, 2) AS STEP_08_TO_09_RATE,
    ROUND(S10::FLOAT / NULLIF(S9, 0) * 100, 2) AS STEP_09_TO_10_RATE,
    ROUND(S11::FLOAT / NULLIF(S10, 0) * 100, 2) AS STEP_10_TO_11_RATE,
    ROUND(S12::FLOAT / NULLIF(S11, 0) * 100, 2) AS STEP_11_TO_12_RATE,
    ROUND(S13::FLOAT / NULLIF(S12, 0) * 100, 2) AS STEP_12_TO_13_RATE,
    ROUND(S14::FLOAT / NULLIF(S13, 0) * 100, 2) AS STEP_13_TO_14_RATE,
    ROUND(S15::FLOAT / NULLIF(S14, 0) * 100, 2) AS STEP_14_TO_15_RATE,
    ROUND(S16::FLOAT / NULLIF(S15, 0) * 100, 2) AS STEP_15_TO_16_RATE,
    ROUND(S17::FLOAT / NULLIF(S16, 0) * 100, 2) AS STEP_16_TO_17_RATE,
    ROUND(S18::FLOAT / NULLIF(S17, 0) * 100, 2) AS STEP_17_TO_18_RATE,
    ROUND(S19::FLOAT / NULLIF(S18, 0) * 100, 2) AS STEP_18_TO_19_RATE,
    ROUND(S19::FLOAT / NULLIF(S1, 0) * 100, 2) AS OVERALL_COMPLETION_RATE
FROM step_counts;

-- =============================================
-- VIEW: Drop-off Analysis
-- =============================================

CREATE OR REPLACE VIEW ANALYTICS.V_FUNNEL_DROPOFF_ANALYSIS AS
SELECT 
    dfs.STEP_NUMBER,
    dfs.STEP_CODE,
    dfs.STEP_NAME,
    dfs.STEP_CATEGORY,
    COUNT(*) AS DROP_OFF_COUNT,
    ROUND(COUNT(*)::FLOAT / SUM(COUNT(*)) OVER () * 100, 2) AS DROP_OFF_PCT,
    AVG(ffs.TOTAL_DURATION_SECONDS) AS AVG_SESSION_DURATION_AT_DROPOFF
FROM ANALYTICS.FACT_FUNNEL_SESSION ffs
JOIN ANALYTICS.DIM_FUNNEL_STEP dfs ON ffs.DROP_OFF_STEP = dfs.STEP_NUMBER
WHERE ffs.IS_COMPLETE = FALSE
GROUP BY dfs.STEP_NUMBER, dfs.STEP_CODE, dfs.STEP_NAME, dfs.STEP_CATEGORY
ORDER BY DROP_OFF_COUNT DESC;

SELECT 'Funnel tracking tables and views created successfully' AS STATUS;
