-- =============================================
-- Clublabs Intelligence - Task Configuration
-- Scheduled transformation from RAW to ANALYTICS
-- =============================================

USE ROLE ACCOUNTADMIN;
USE DATABASE CLUBLABS_INTELLIGENCE;
USE WAREHOUSE CLUBLABS_WH;

-- =============================================
-- TASK: Transform chatbot logs to conversations
-- Runs every 5 minutes when stream has data
-- =============================================

CREATE OR REPLACE TASK STAGING.TRANSFORM_CHATBOT_LOGS
    WAREHOUSE = CLUBLABS_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('RAW.CHATBOT_LOGS_STREAM')
    AS
    MERGE INTO ANALYTICS.FACT_CONVERSATION AS target
    USING (
        WITH parsed_logs AS (
            SELECT 
                LOG_ID,
                TIMESTAMP,
                SESSION_ID,
                MEMBER_ID,
                EVENT_TYPE,
                EVENT_DATA,
                CHANNEL,
                RAW_PAYLOAD,
                RAW_PAYLOAD:conversation_id::VARCHAR AS CONVERSATION_ID,
                RAW_PAYLOAD:duration_seconds::NUMBER AS DURATION_SECONDS,
                RAW_PAYLOAD:message_count::NUMBER AS MESSAGE_COUNT,
                RAW_PAYLOAD:bot_message_count::NUMBER AS BOT_MESSAGE_COUNT,
                RAW_PAYLOAD:human_message_count::NUMBER AS HUMAN_MESSAGE_COUNT,
                RAW_PAYLOAD:member_message_count::NUMBER AS MEMBER_MESSAGE_COUNT,
                RAW_PAYLOAD:was_escalated::BOOLEAN AS WAS_ESCALATED,
                RAW_PAYLOAD:escalation_reason::VARCHAR AS ESCALATION_REASON,
                RAW_PAYLOAD:resolution_status::VARCHAR AS RESOLUTION_STATUS,
                RAW_PAYLOAD:first_contact_resolution::BOOLEAN AS FIRST_CONTACT_RESOLUTION,
                RAW_PAYLOAD:sentiment_score::FLOAT AS SENTIMENT_SCORE,
                RAW_PAYLOAD:csat_score::NUMBER AS CSAT_SCORE,
                RAW_PAYLOAD:intent_detected::VARCHAR AS INTENT_DETECTED,
                RAW_PAYLOAD:confidence_score::FLOAT AS CONFIDENCE_SCORE,
                RAW_PAYLOAD:service_type::VARCHAR AS SERVICE_TYPE
            FROM RAW.CHATBOT_LOGS_STREAM
            WHERE EVENT_TYPE = 'CONVERSATION_END'
        ),
        enriched AS (
            SELECT 
                pl.*,
                TO_NUMBER(TO_CHAR(pl.TIMESTAMP, 'YYYYMMDD')) AS DATE_KEY,
                COALESCE(dm.MEMBER_KEY, -1) AS MEMBER_KEY,
                COALESCE(dst.SERVICE_TYPE_KEY, -1) AS SERVICE_TYPE_KEY,
                COALESCE(dc.CHANNEL_KEY, -1) AS CHANNEL_KEY,
                CASE 
                    WHEN pl.SENTIMENT_SCORE < -0.3 THEN 'NEGATIVE'
                    WHEN pl.SENTIMENT_SCORE > 0.3 THEN 'POSITIVE'
                    ELSE 'NEUTRAL'
                END AS SENTIMENT_LABEL
            FROM parsed_logs pl
            LEFT JOIN ANALYTICS.DIM_MEMBER dm ON pl.MEMBER_ID = dm.MEMBER_ID
            LEFT JOIN ANALYTICS.DIM_SERVICE_TYPE dst ON pl.SERVICE_TYPE = dst.SERVICE_CODE
            LEFT JOIN ANALYTICS.DIM_CHANNEL dc ON UPPER(pl.CHANNEL) = dc.CHANNEL_CODE
        )
        SELECT * FROM enriched
    ) AS source
    ON target.CONVERSATION_ID = source.CONVERSATION_ID
    WHEN NOT MATCHED THEN
        INSERT (
            CONVERSATION_ID, DATE_KEY, MEMBER_KEY, SERVICE_TYPE_KEY, CHANNEL_KEY,
            INITIAL_AGENT_KEY, FINAL_AGENT_KEY, START_TIMESTAMP, END_TIMESTAMP,
            DURATION_SECONDS, MESSAGE_COUNT, BOT_MESSAGE_COUNT, HUMAN_MESSAGE_COUNT,
            MEMBER_MESSAGE_COUNT, WAS_ESCALATED, ESCALATION_REASON, RESOLUTION_STATUS,
            FIRST_CONTACT_RESOLUTION, SENTIMENT_SCORE, SENTIMENT_LABEL, CSAT_SCORE,
            INTENT_DETECTED, CONFIDENCE_SCORE
        )
        VALUES (
            source.CONVERSATION_ID, source.DATE_KEY, source.MEMBER_KEY, 
            source.SERVICE_TYPE_KEY, source.CHANNEL_KEY,
            1, CASE WHEN source.WAS_ESCALATED THEN 3 ELSE 1 END,
            source.TIMESTAMP, source.TIMESTAMP,
            source.DURATION_SECONDS, source.MESSAGE_COUNT, source.BOT_MESSAGE_COUNT,
            source.HUMAN_MESSAGE_COUNT, source.MEMBER_MESSAGE_COUNT, source.WAS_ESCALATED,
            source.ESCALATION_REASON, source.RESOLUTION_STATUS, source.FIRST_CONTACT_RESOLUTION,
            source.SENTIMENT_SCORE, source.SENTIMENT_LABEL, source.CSAT_SCORE,
            source.INTENT_DETECTED, source.CONFIDENCE_SCORE
        );

-- =============================================
-- TASK: Aggregate daily KPIs
-- Runs daily at 1 AM
-- =============================================

CREATE OR REPLACE TASK STAGING.AGGREGATE_DAILY_KPIS
    WAREHOUSE = CLUBLABS_WH
    SCHEDULE = 'USING CRON 0 1 * * * America/New_York'
    AS
    MERGE INTO ANALYTICS.FACT_DAILY_KPI AS target
    USING (
        SELECT 
            fc.DATE_KEY,
            fc.CHANNEL_KEY,
            fc.SERVICE_TYPE_KEY,
            COUNT(*) AS TOTAL_CONVERSATIONS,
            SUM(fc.MESSAGE_COUNT) AS TOTAL_MESSAGES,
            SUM(CASE WHEN NOT fc.WAS_ESCALATED THEN 1 ELSE 0 END) AS BOT_HANDLED_COUNT,
            SUM(CASE WHEN fc.WAS_ESCALATED THEN 1 ELSE 0 END) AS ESCALATED_COUNT,
            SUM(CASE WHEN fc.RESOLUTION_STATUS = 'ABANDONED' THEN 1 ELSE 0 END) AS ABANDONED_COUNT,
            AVG(fc.DURATION_SECONDS) AS AVG_DURATION_SECONDS,
            AVG(fc.MESSAGE_COUNT) / NULLIF(AVG(fc.DURATION_SECONDS), 0) * 60 AS AVG_RESPONSE_TIME_SECONDS,
            AVG(fc.MESSAGE_COUNT) AS AVG_MESSAGE_COUNT,
            SUM(CASE WHEN NOT fc.WAS_ESCALATED THEN 1 ELSE 0 END)::FLOAT / NULLIF(COUNT(*), 0) AS CONTAINMENT_RATE,
            SUM(CASE WHEN fc.WAS_ESCALATED THEN 1 ELSE 0 END)::FLOAT / NULLIF(COUNT(*), 0) AS ESCALATION_RATE,
            SUM(CASE WHEN fc.RESOLUTION_STATUS = 'ABANDONED' THEN 1 ELSE 0 END)::FLOAT / NULLIF(COUNT(*), 0) AS ABANDONMENT_RATE,
            SUM(CASE WHEN fc.FIRST_CONTACT_RESOLUTION THEN 1 ELSE 0 END)::FLOAT / NULLIF(COUNT(*), 0) AS FCR_RATE,
            AVG(fc.SENTIMENT_SCORE) AS AVG_SENTIMENT_SCORE,
            AVG(fc.CSAT_SCORE) AS AVG_CSAT_SCORE,
            SUM(CASE WHEN fc.SENTIMENT_LABEL = 'POSITIVE' THEN 1 ELSE 0 END) AS POSITIVE_SENTIMENT_COUNT,
            SUM(CASE WHEN fc.SENTIMENT_LABEL = 'NEGATIVE' THEN 1 ELSE 0 END) AS NEGATIVE_SENTIMENT_COUNT,
            SUM(CASE WHEN fc.SENTIMENT_LABEL = 'NEUTRAL' THEN 1 ELSE 0 END) AS NEUTRAL_SENTIMENT_COUNT
        FROM ANALYTICS.FACT_CONVERSATION fc
        WHERE fc.DATE_KEY = TO_NUMBER(TO_CHAR(DATEADD(DAY, -1, CURRENT_DATE()), 'YYYYMMDD'))
        GROUP BY fc.DATE_KEY, fc.CHANNEL_KEY, fc.SERVICE_TYPE_KEY
    ) AS source
    ON target.DATE_KEY = source.DATE_KEY 
       AND target.CHANNEL_KEY = source.CHANNEL_KEY 
       AND target.SERVICE_TYPE_KEY = source.SERVICE_TYPE_KEY
    WHEN MATCHED THEN UPDATE SET
        TOTAL_CONVERSATIONS = source.TOTAL_CONVERSATIONS,
        TOTAL_MESSAGES = source.TOTAL_MESSAGES,
        BOT_HANDLED_COUNT = source.BOT_HANDLED_COUNT,
        ESCALATED_COUNT = source.ESCALATED_COUNT,
        ABANDONED_COUNT = source.ABANDONED_COUNT,
        AVG_DURATION_SECONDS = source.AVG_DURATION_SECONDS,
        AVG_RESPONSE_TIME_SECONDS = source.AVG_RESPONSE_TIME_SECONDS,
        AVG_MESSAGE_COUNT = source.AVG_MESSAGE_COUNT,
        CONTAINMENT_RATE = source.CONTAINMENT_RATE,
        ESCALATION_RATE = source.ESCALATION_RATE,
        ABANDONMENT_RATE = source.ABANDONMENT_RATE,
        FCR_RATE = source.FCR_RATE,
        AVG_SENTIMENT_SCORE = source.AVG_SENTIMENT_SCORE,
        AVG_CSAT_SCORE = source.AVG_CSAT_SCORE,
        POSITIVE_SENTIMENT_COUNT = source.POSITIVE_SENTIMENT_COUNT,
        NEGATIVE_SENTIMENT_COUNT = source.NEGATIVE_SENTIMENT_COUNT,
        NEUTRAL_SENTIMENT_COUNT = source.NEUTRAL_SENTIMENT_COUNT
    WHEN NOT MATCHED THEN INSERT (
        DATE_KEY, CHANNEL_KEY, SERVICE_TYPE_KEY, TOTAL_CONVERSATIONS, TOTAL_MESSAGES,
        BOT_HANDLED_COUNT, ESCALATED_COUNT, ABANDONED_COUNT, AVG_DURATION_SECONDS,
        AVG_RESPONSE_TIME_SECONDS, AVG_MESSAGE_COUNT, CONTAINMENT_RATE, ESCALATION_RATE,
        ABANDONMENT_RATE, FCR_RATE, AVG_SENTIMENT_SCORE, AVG_CSAT_SCORE,
        POSITIVE_SENTIMENT_COUNT, NEGATIVE_SENTIMENT_COUNT, NEUTRAL_SENTIMENT_COUNT
    )
    VALUES (
        source.DATE_KEY, source.CHANNEL_KEY, source.SERVICE_TYPE_KEY, 
        source.TOTAL_CONVERSATIONS, source.TOTAL_MESSAGES,
        source.BOT_HANDLED_COUNT, source.ESCALATED_COUNT, source.ABANDONED_COUNT, 
        source.AVG_DURATION_SECONDS, source.AVG_RESPONSE_TIME_SECONDS, source.AVG_MESSAGE_COUNT, 
        source.CONTAINMENT_RATE, source.ESCALATION_RATE, source.ABANDONMENT_RATE, source.FCR_RATE, 
        source.AVG_SENTIMENT_SCORE, source.AVG_CSAT_SCORE,
        source.POSITIVE_SENTIMENT_COUNT, source.NEGATIVE_SENTIMENT_COUNT, source.NEUTRAL_SENTIMENT_COUNT
    );

-- =============================================
-- ENABLE TASKS
-- =============================================

ALTER TASK STAGING.TRANSFORM_CHATBOT_LOGS RESUME;
ALTER TASK STAGING.AGGREGATE_DAILY_KPIS RESUME;

-- =============================================
-- VERIFY TASKS
-- =============================================

SHOW TASKS IN SCHEMA STAGING;

-- Check task history
SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME IN ('TRANSFORM_CHATBOT_LOGS', 'AGGREGATE_DAILY_KPIS')
ORDER BY SCHEDULED_TIME DESC
LIMIT 10;

SELECT 'Task configuration complete' AS STATUS;
