-- =============================================
-- Clublabs Intelligence Agent - Analytical Views
-- Step 4: Create views for KPI dashboards and analysis
-- =============================================

USE ROLE ACCOUNTADMIN;
USE DATABASE CLUBLABS_INTELLIGENCE;
USE WAREHOUSE CLUBLABS_WH;

-- =============================================
-- OPERATIONAL VIEWS
-- =============================================

-- Real-time chatbot performance dashboard view
CREATE OR REPLACE VIEW ANALYTICS.V_CHATBOT_PERFORMANCE AS
SELECT 
    dd.FULL_DATE AS DATE,
    dd.DAY_NAME,
    dd.MONTH_NAME,
    dd.YEAR,
    dc.CHANNEL_NAME,
    dst.SERVICE_CATEGORY,
    
    COUNT(fc.CONVERSATION_KEY) AS TOTAL_CONVERSATIONS,
    SUM(fc.MESSAGE_COUNT) AS TOTAL_MESSAGES,
    
    SUM(CASE WHEN fc.WAS_ESCALATED THEN 0 ELSE 1 END) AS BOT_CONTAINED_COUNT,
    SUM(CASE WHEN fc.WAS_ESCALATED THEN 1 ELSE 0 END) AS ESCALATED_COUNT,
    SUM(CASE WHEN fc.RESOLUTION_STATUS = 'ABANDONED' THEN 1 ELSE 0 END) AS ABANDONED_COUNT,
    
    ROUND(AVG(fc.DURATION_SECONDS), 2) AS AVG_DURATION_SECONDS,
    ROUND(AVG(fc.MESSAGE_COUNT), 2) AS AVG_MESSAGES_PER_CONVERSATION,
    
    ROUND(SUM(CASE WHEN fc.WAS_ESCALATED THEN 0 ELSE 1 END)::FLOAT / NULLIF(COUNT(*), 0) * 100, 2) AS CONTAINMENT_RATE_PCT,
    ROUND(SUM(CASE WHEN fc.WAS_ESCALATED THEN 1 ELSE 0 END)::FLOAT / NULLIF(COUNT(*), 0) * 100, 2) AS ESCALATION_RATE_PCT,
    ROUND(SUM(CASE WHEN fc.FIRST_CONTACT_RESOLUTION THEN 1 ELSE 0 END)::FLOAT / NULLIF(COUNT(*), 0) * 100, 2) AS FCR_RATE_PCT,
    
    ROUND(AVG(fc.SENTIMENT_SCORE), 3) AS AVG_SENTIMENT_SCORE,
    ROUND(AVG(fc.CSAT_SCORE), 2) AS AVG_CSAT_SCORE,
    
    SUM(CASE WHEN fc.SENTIMENT_LABEL = 'POSITIVE' THEN 1 ELSE 0 END) AS POSITIVE_COUNT,
    SUM(CASE WHEN fc.SENTIMENT_LABEL = 'NEGATIVE' THEN 1 ELSE 0 END) AS NEGATIVE_COUNT,
    SUM(CASE WHEN fc.SENTIMENT_LABEL = 'NEUTRAL' THEN 1 ELSE 0 END) AS NEUTRAL_COUNT
FROM ANALYTICS.FACT_CONVERSATION fc
JOIN ANALYTICS.DIM_DATE dd ON fc.DATE_KEY = dd.DATE_KEY
JOIN ANALYTICS.DIM_CHANNEL dc ON fc.CHANNEL_KEY = dc.CHANNEL_KEY
JOIN ANALYTICS.DIM_SERVICE_TYPE dst ON fc.SERVICE_TYPE_KEY = dst.SERVICE_TYPE_KEY
GROUP BY dd.FULL_DATE, dd.DAY_NAME, dd.MONTH_NAME, dd.YEAR, dc.CHANNEL_NAME, dst.SERVICE_CATEGORY;

-- Escalation analysis view
CREATE OR REPLACE VIEW ANALYTICS.V_ESCALATION_ANALYSIS AS
SELECT 
    dd.FULL_DATE AS DATE,
    dc.CHANNEL_NAME,
    dst.SERVICE_CATEGORY,
    dst.SERVICE_NAME,
    dm.MEMBERSHIP_TYPE,
    dm.REGION,
    
    COUNT(fc.CONVERSATION_KEY) AS TOTAL_ESCALATIONS,
    fc.ESCALATION_REASON,
    
    ROUND(AVG(fc.DURATION_SECONDS), 2) AS AVG_DURATION_BEFORE_ESCALATION,
    ROUND(AVG(fc.MESSAGE_COUNT), 2) AS AVG_MESSAGES_BEFORE_ESCALATION,
    ROUND(AVG(fc.SENTIMENT_SCORE), 3) AS AVG_SENTIMENT_AT_ESCALATION,
    
    da_initial.AGENT_NAME AS INITIAL_BOT,
    da_final.AGENT_NAME AS ESCALATED_TO_AGENT
FROM ANALYTICS.FACT_CONVERSATION fc
JOIN ANALYTICS.DIM_DATE dd ON fc.DATE_KEY = dd.DATE_KEY
JOIN ANALYTICS.DIM_CHANNEL dc ON fc.CHANNEL_KEY = dc.CHANNEL_KEY
JOIN ANALYTICS.DIM_SERVICE_TYPE dst ON fc.SERVICE_TYPE_KEY = dst.SERVICE_TYPE_KEY
JOIN ANALYTICS.DIM_MEMBER dm ON fc.MEMBER_KEY = dm.MEMBER_KEY
JOIN ANALYTICS.DIM_AGENT da_initial ON fc.INITIAL_AGENT_KEY = da_initial.AGENT_KEY
JOIN ANALYTICS.DIM_AGENT da_final ON fc.FINAL_AGENT_KEY = da_final.AGENT_KEY
WHERE fc.WAS_ESCALATED = TRUE
GROUP BY dd.FULL_DATE, dc.CHANNEL_NAME, dst.SERVICE_CATEGORY, dst.SERVICE_NAME,
         dm.MEMBERSHIP_TYPE, dm.REGION, fc.ESCALATION_REASON, da_initial.AGENT_NAME, da_final.AGENT_NAME;

-- Member engagement analysis view
CREATE OR REPLACE VIEW ANALYTICS.V_MEMBER_ENGAGEMENT AS
SELECT 
    dm.MEMBER_ID,
    dm.MEMBERSHIP_TYPE,
    dm.REGION,
    dm.STATE,
    dm.TENURE_MONTHS,
    dm.AGE_GROUP,
    
    COUNT(fc.CONVERSATION_KEY) AS TOTAL_INTERACTIONS,
    COUNT(DISTINCT fc.DATE_KEY) AS ACTIVE_DAYS,
    
    MIN(dd.FULL_DATE) AS FIRST_INTERACTION_DATE,
    MAX(dd.FULL_DATE) AS LAST_INTERACTION_DATE,
    
    ROUND(AVG(fc.SENTIMENT_SCORE), 3) AS AVG_SENTIMENT,
    ROUND(AVG(fc.CSAT_SCORE), 2) AS AVG_CSAT,
    
    SUM(CASE WHEN fc.WAS_ESCALATED THEN 1 ELSE 0 END) AS ESCALATION_COUNT,
    SUM(CASE WHEN fc.FIRST_CONTACT_RESOLUTION THEN 1 ELSE 0 END) AS FCR_COUNT,
    
    ARRAY_AGG(DISTINCT dst.SERVICE_CATEGORY) AS SERVICE_CATEGORIES_USED
FROM ANALYTICS.DIM_MEMBER dm
JOIN ANALYTICS.FACT_CONVERSATION fc ON dm.MEMBER_KEY = fc.MEMBER_KEY
JOIN ANALYTICS.DIM_DATE dd ON fc.DATE_KEY = dd.DATE_KEY
JOIN ANALYTICS.DIM_SERVICE_TYPE dst ON fc.SERVICE_TYPE_KEY = dst.SERVICE_TYPE_KEY
GROUP BY dm.MEMBER_ID, dm.MEMBERSHIP_TYPE, dm.REGION, dm.STATE, dm.TENURE_MONTHS, dm.AGE_GROUP;

-- Service type performance view
CREATE OR REPLACE VIEW ANALYTICS.V_SERVICE_PERFORMANCE AS
SELECT 
    dst.SERVICE_CODE,
    dst.SERVICE_NAME,
    dst.SERVICE_CATEGORY,
    dst.IS_EMERGENCY,
    dst.AVERAGE_RESOLUTION_MINUTES AS EXPECTED_RESOLUTION_MINUTES,
    
    COUNT(fc.CONVERSATION_KEY) AS TOTAL_REQUESTS,
    
    ROUND(AVG(fc.DURATION_SECONDS / 60.0), 2) AS ACTUAL_AVG_RESOLUTION_MINUTES,
    
    ROUND(SUM(CASE WHEN fc.WAS_ESCALATED THEN 0 ELSE 1 END)::FLOAT / NULLIF(COUNT(*), 0) * 100, 2) AS CONTAINMENT_RATE_PCT,
    ROUND(SUM(CASE WHEN fc.FIRST_CONTACT_RESOLUTION THEN 1 ELSE 0 END)::FLOAT / NULLIF(COUNT(*), 0) * 100, 2) AS FCR_RATE_PCT,
    
    ROUND(AVG(fc.SENTIMENT_SCORE), 3) AS AVG_SENTIMENT,
    ROUND(AVG(fc.CSAT_SCORE), 2) AS AVG_CSAT,
    
    COUNT(DISTINCT fc.MEMBER_KEY) AS UNIQUE_MEMBERS
FROM ANALYTICS.DIM_SERVICE_TYPE dst
JOIN ANALYTICS.FACT_CONVERSATION fc ON dst.SERVICE_TYPE_KEY = fc.SERVICE_TYPE_KEY
GROUP BY dst.SERVICE_CODE, dst.SERVICE_NAME, dst.SERVICE_CATEGORY, dst.IS_EMERGENCY, dst.AVERAGE_RESOLUTION_MINUTES;

-- User journey funnel view
CREATE OR REPLACE VIEW ANALYTICS.V_USER_FUNNEL AS
SELECT 
    dd.FULL_DATE AS DATE,
    dd.MONTH_NAME,
    dd.YEAR,
    dc.CHANNEL_NAME,
    
    COUNT(fuj.JOURNEY_KEY) AS TOTAL_JOURNEYS,
    
    SUM(CASE WHEN fuj.STEP_1_LANDING THEN 1 ELSE 0 END) AS STEP_1_LANDING,
    SUM(CASE WHEN fuj.STEP_2_CHAT_INITIATED THEN 1 ELSE 0 END) AS STEP_2_CHAT_INITIATED,
    SUM(CASE WHEN fuj.STEP_3_INTENT_IDENTIFIED THEN 1 ELSE 0 END) AS STEP_3_INTENT_IDENTIFIED,
    SUM(CASE WHEN fuj.STEP_4_SOLUTION_PROVIDED THEN 1 ELSE 0 END) AS STEP_4_SOLUTION_PROVIDED,
    SUM(CASE WHEN fuj.STEP_5_RESOLUTION_ACHIEVED THEN 1 ELSE 0 END) AS STEP_5_RESOLUTION_ACHIEVED,
    
    ROUND(SUM(CASE WHEN fuj.STEP_2_CHAT_INITIATED THEN 1 ELSE 0 END)::FLOAT / NULLIF(SUM(CASE WHEN fuj.STEP_1_LANDING THEN 1 ELSE 0 END), 0) * 100, 2) AS STEP_1_TO_2_RATE,
    ROUND(SUM(CASE WHEN fuj.STEP_5_RESOLUTION_ACHIEVED THEN 1 ELSE 0 END)::FLOAT / NULLIF(SUM(CASE WHEN fuj.STEP_1_LANDING THEN 1 ELSE 0 END), 0) * 100, 2) AS OVERALL_CONVERSION_RATE,
    
    ROUND(AVG(fuj.TIME_TO_RESOLUTION_SECONDS), 2) AS AVG_TIME_TO_RESOLUTION_SECONDS,
    
    SUM(CASE WHEN fuj.CONVERSION_FLAG THEN 1 ELSE 0 END) AS CONVERSIONS
FROM ANALYTICS.FACT_USER_JOURNEY fuj
JOIN ANALYTICS.DIM_DATE dd ON fuj.DATE_KEY = dd.DATE_KEY
JOIN ANALYTICS.DIM_CHANNEL dc ON fuj.CHANNEL_KEY = dc.CHANNEL_KEY
GROUP BY dd.FULL_DATE, dd.MONTH_NAME, dd.YEAR, dc.CHANNEL_NAME;

-- Daily trends view
CREATE OR REPLACE VIEW ANALYTICS.V_DAILY_TRENDS AS
SELECT 
    dd.FULL_DATE AS DATE,
    dd.DAY_NAME,
    dd.WEEK_OF_YEAR,
    dd.MONTH_NAME,
    dd.QUARTER,
    dd.YEAR,
    dd.IS_WEEKEND,
    
    COUNT(fc.CONVERSATION_KEY) AS TOTAL_CONVERSATIONS,
    SUM(fc.MESSAGE_COUNT) AS TOTAL_MESSAGES,
    
    ROUND(SUM(CASE WHEN fc.WAS_ESCALATED THEN 0 ELSE 1 END)::FLOAT / NULLIF(COUNT(*), 0) * 100, 2) AS CONTAINMENT_RATE_PCT,
    ROUND(AVG(fc.SENTIMENT_SCORE), 3) AS AVG_SENTIMENT,
    ROUND(AVG(fc.CSAT_SCORE), 2) AS AVG_CSAT,
    
    COUNT(DISTINCT fc.MEMBER_KEY) AS UNIQUE_MEMBERS,
    
    LAG(COUNT(fc.CONVERSATION_KEY), 1) OVER (ORDER BY dd.FULL_DATE) AS PREV_DAY_CONVERSATIONS,
    LAG(COUNT(fc.CONVERSATION_KEY), 7) OVER (ORDER BY dd.FULL_DATE) AS SAME_DAY_LAST_WEEK_CONVERSATIONS
FROM ANALYTICS.FACT_CONVERSATION fc
JOIN ANALYTICS.DIM_DATE dd ON fc.DATE_KEY = dd.DATE_KEY
GROUP BY dd.FULL_DATE, dd.DAY_NAME, dd.WEEK_OF_YEAR, dd.MONTH_NAME, dd.QUARTER, dd.YEAR, dd.IS_WEEKEND;

-- Hourly distribution view
CREATE OR REPLACE VIEW ANALYTICS.V_HOURLY_DISTRIBUTION AS
SELECT 
    HOUR(fc.START_TIMESTAMP) AS HOUR_OF_DAY,
    dd.DAY_NAME,
    dd.IS_WEEKEND,
    
    COUNT(fc.CONVERSATION_KEY) AS TOTAL_CONVERSATIONS,
    ROUND(AVG(fc.DURATION_SECONDS), 2) AS AVG_DURATION_SECONDS,
    ROUND(SUM(CASE WHEN fc.WAS_ESCALATED THEN 1 ELSE 0 END)::FLOAT / NULLIF(COUNT(*), 0) * 100, 2) AS ESCALATION_RATE_PCT,
    ROUND(AVG(fc.SENTIMENT_SCORE), 3) AS AVG_SENTIMENT
FROM ANALYTICS.FACT_CONVERSATION fc
JOIN ANALYTICS.DIM_DATE dd ON fc.DATE_KEY = dd.DATE_KEY
GROUP BY HOUR(fc.START_TIMESTAMP), dd.DAY_NAME, dd.IS_WEEKEND;

SELECT 'Analytical views created successfully' AS STATUS;
