-- =============================================
-- Clublabs Intelligence Agent - Table Definitions
-- Step 2: Create tables for ERS chatbot analytics
-- =============================================

USE ROLE ACCOUNTADMIN;
USE DATABASE CLUBLABS_INTELLIGENCE;
USE WAREHOUSE CLUBLABS_WH;

-- =============================================
-- DIMENSION TABLES (ANALYTICS Schema)
-- =============================================

-- Date dimension for time-series analysis
CREATE OR REPLACE TABLE ANALYTICS.DIM_DATE (
    DATE_KEY NUMBER(8) PRIMARY KEY,
    FULL_DATE DATE NOT NULL,
    DAY_OF_WEEK NUMBER(1),
    DAY_NAME VARCHAR(10),
    DAY_OF_MONTH NUMBER(2),
    DAY_OF_YEAR NUMBER(3),
    WEEK_OF_YEAR NUMBER(2),
    MONTH_NUMBER NUMBER(2),
    MONTH_NAME VARCHAR(10),
    QUARTER NUMBER(1),
    YEAR NUMBER(4),
    IS_WEEKEND BOOLEAN,
    IS_HOLIDAY BOOLEAN
);

-- Member dimension
CREATE OR REPLACE TABLE ANALYTICS.DIM_MEMBER (
    MEMBER_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    MEMBER_ID VARCHAR(50) NOT NULL UNIQUE,
    MEMBERSHIP_TYPE VARCHAR(20),          -- Basic, Plus, Premier
    REGION VARCHAR(50),
    STATE VARCHAR(2),
    JOIN_DATE DATE,
    TENURE_MONTHS NUMBER,
    AGE_GROUP VARCHAR(20),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Service type dimension
CREATE OR REPLACE TABLE ANALYTICS.DIM_SERVICE_TYPE (
    SERVICE_TYPE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    SERVICE_CODE VARCHAR(20) NOT NULL UNIQUE,
    SERVICE_NAME VARCHAR(100),
    SERVICE_CATEGORY VARCHAR(50),         -- Roadside, Travel, Insurance, etc.
    IS_EMERGENCY BOOLEAN,
    AVERAGE_RESOLUTION_MINUTES NUMBER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Channel dimension
CREATE OR REPLACE TABLE ANALYTICS.DIM_CHANNEL (
    CHANNEL_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CHANNEL_CODE VARCHAR(20) NOT NULL UNIQUE,
    CHANNEL_NAME VARCHAR(50),             -- Web Chat, Mobile App, IVR, Phone
    IS_DIGITAL BOOLEAN,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Agent dimension (chatbot vs human)
CREATE OR REPLACE TABLE ANALYTICS.DIM_AGENT (
    AGENT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    AGENT_ID VARCHAR(50) NOT NULL UNIQUE,
    AGENT_TYPE VARCHAR(20),               -- BOT, HUMAN
    AGENT_NAME VARCHAR(100),
    DEPARTMENT VARCHAR(50),
    SKILL_LEVEL VARCHAR(20),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================
-- FACT TABLES (ANALYTICS Schema)
-- =============================================

-- Main conversation fact table
CREATE OR REPLACE TABLE ANALYTICS.FACT_CONVERSATION (
    CONVERSATION_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CONVERSATION_ID VARCHAR(50) NOT NULL UNIQUE,
    DATE_KEY NUMBER(8) REFERENCES ANALYTICS.DIM_DATE(DATE_KEY),
    MEMBER_KEY NUMBER REFERENCES ANALYTICS.DIM_MEMBER(MEMBER_KEY),
    SERVICE_TYPE_KEY NUMBER REFERENCES ANALYTICS.DIM_SERVICE_TYPE(SERVICE_TYPE_KEY),
    CHANNEL_KEY NUMBER REFERENCES ANALYTICS.DIM_CHANNEL(CHANNEL_KEY),
    INITIAL_AGENT_KEY NUMBER REFERENCES ANALYTICS.DIM_AGENT(AGENT_KEY),
    FINAL_AGENT_KEY NUMBER REFERENCES ANALYTICS.DIM_AGENT(AGENT_KEY),
    
    START_TIMESTAMP TIMESTAMP_NTZ,
    END_TIMESTAMP TIMESTAMP_NTZ,
    DURATION_SECONDS NUMBER,
    
    MESSAGE_COUNT NUMBER,
    BOT_MESSAGE_COUNT NUMBER,
    HUMAN_MESSAGE_COUNT NUMBER,
    MEMBER_MESSAGE_COUNT NUMBER,
    
    WAS_ESCALATED BOOLEAN DEFAULT FALSE,
    ESCALATION_REASON VARCHAR(200),
    ESCALATION_TIMESTAMP TIMESTAMP_NTZ,
    
    RESOLUTION_STATUS VARCHAR(20),        -- RESOLVED, ESCALATED, ABANDONED, PENDING
    FIRST_CONTACT_RESOLUTION BOOLEAN,
    
    SENTIMENT_SCORE FLOAT,                -- -1 to 1
    SENTIMENT_LABEL VARCHAR(20),          -- NEGATIVE, NEUTRAL, POSITIVE
    CSAT_SCORE NUMBER(1),                 -- 1-5
    
    INTENT_DETECTED VARCHAR(100),
    CONFIDENCE_SCORE FLOAT,
    
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Message-level detail fact table
CREATE OR REPLACE TABLE ANALYTICS.FACT_MESSAGE (
    MESSAGE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    MESSAGE_ID VARCHAR(50) NOT NULL UNIQUE,
    CONVERSATION_KEY NUMBER REFERENCES ANALYTICS.FACT_CONVERSATION(CONVERSATION_KEY),
    
    MESSAGE_TIMESTAMP TIMESTAMP_NTZ,
    MESSAGE_SEQUENCE NUMBER,
    
    SENDER_TYPE VARCHAR(20),              -- MEMBER, BOT, HUMAN_AGENT
    AGENT_KEY NUMBER REFERENCES ANALYTICS.DIM_AGENT(AGENT_KEY),
    
    MESSAGE_TEXT TEXT,
    MESSAGE_LENGTH NUMBER,
    
    RESPONSE_TIME_SECONDS NUMBER,
    
    INTENT_DETECTED VARCHAR(100),
    CONFIDENCE_SCORE FLOAT,
    SENTIMENT_SCORE FLOAT,
    
    CONTAINS_PII BOOLEAN DEFAULT FALSE,
    WAS_HELPFUL BOOLEAN,
    
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- User journey/funnel fact table
CREATE OR REPLACE TABLE ANALYTICS.FACT_USER_JOURNEY (
    JOURNEY_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    SESSION_ID VARCHAR(50) NOT NULL,
    MEMBER_KEY NUMBER REFERENCES ANALYTICS.DIM_MEMBER(MEMBER_KEY),
    DATE_KEY NUMBER(8) REFERENCES ANALYTICS.DIM_DATE(DATE_KEY),
    CHANNEL_KEY NUMBER REFERENCES ANALYTICS.DIM_CHANNEL(CHANNEL_KEY),
    
    JOURNEY_START TIMESTAMP_NTZ,
    JOURNEY_END TIMESTAMP_NTZ,
    
    STEP_1_LANDING BOOLEAN DEFAULT FALSE,
    STEP_2_CHAT_INITIATED BOOLEAN DEFAULT FALSE,
    STEP_3_INTENT_IDENTIFIED BOOLEAN DEFAULT FALSE,
    STEP_4_SOLUTION_PROVIDED BOOLEAN DEFAULT FALSE,
    STEP_5_RESOLUTION_ACHIEVED BOOLEAN DEFAULT FALSE,
    
    DROP_OFF_STEP NUMBER,
    DROP_OFF_REASON VARCHAR(200),
    
    TOTAL_INTERACTIONS NUMBER,
    PAGES_VIEWED NUMBER,
    TIME_TO_RESOLUTION_SECONDS NUMBER,
    
    CONVERSION_FLAG BOOLEAN DEFAULT FALSE,
    CONVERSION_TYPE VARCHAR(50),
    
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Daily KPI aggregation table
CREATE OR REPLACE TABLE ANALYTICS.FACT_DAILY_KPI (
    KPI_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    DATE_KEY NUMBER(8) REFERENCES ANALYTICS.DIM_DATE(DATE_KEY),
    CHANNEL_KEY NUMBER REFERENCES ANALYTICS.DIM_CHANNEL(CHANNEL_KEY),
    SERVICE_TYPE_KEY NUMBER REFERENCES ANALYTICS.DIM_SERVICE_TYPE(SERVICE_TYPE_KEY),
    
    TOTAL_CONVERSATIONS NUMBER,
    TOTAL_MESSAGES NUMBER,
    
    BOT_HANDLED_COUNT NUMBER,
    ESCALATED_COUNT NUMBER,
    ABANDONED_COUNT NUMBER,
    
    AVG_DURATION_SECONDS FLOAT,
    AVG_RESPONSE_TIME_SECONDS FLOAT,
    AVG_MESSAGE_COUNT FLOAT,
    
    CONTAINMENT_RATE FLOAT,               -- % handled by bot without escalation
    ESCALATION_RATE FLOAT,
    ABANDONMENT_RATE FLOAT,
    FCR_RATE FLOAT,                       -- First Contact Resolution
    
    AVG_SENTIMENT_SCORE FLOAT,
    AVG_CSAT_SCORE FLOAT,
    
    POSITIVE_SENTIMENT_COUNT NUMBER,
    NEGATIVE_SENTIMENT_COUNT NUMBER,
    NEUTRAL_SENTIMENT_COUNT NUMBER,
    
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================
-- RAW/STAGING TABLES
-- =============================================

-- Raw conversation logs from ERS chatbot
CREATE OR REPLACE TABLE RAW.CHATBOT_LOGS (
    LOG_ID VARCHAR(50),
    TIMESTAMP TIMESTAMP_NTZ,
    SESSION_ID VARCHAR(50),
    MEMBER_ID VARCHAR(50),
    EVENT_TYPE VARCHAR(50),
    EVENT_DATA VARIANT,
    CHANNEL VARCHAR(20),
    RAW_PAYLOAD VARIANT,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Raw conversation transcripts for search
CREATE OR REPLACE TABLE RAW.CONVERSATION_TRANSCRIPTS (
    TRANSCRIPT_ID VARCHAR(50) PRIMARY KEY,
    CONVERSATION_ID VARCHAR(50),
    MEMBER_ID VARCHAR(50),
    FULL_TRANSCRIPT TEXT,
    TRANSCRIPT_SUMMARY TEXT,
    KEY_TOPICS ARRAY,
    SERVICE_CATEGORY VARCHAR(50),
    RESOLUTION_NOTES TEXT,
    CONVERSATION_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

SELECT 'Table creation complete' AS STATUS;
